version: '3.9'

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy-agent
    restart: always
    environment:
      - NODE_NAME=${NODE_NAME:-node-default}
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME:-default-tenant}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/log:/var/log:ro
    command:
      - "run"
      - "--server.http.listen-addr=127.0.0.1:12345"
      - "/etc/alloy/config.alloy"
    network_mode: "host"
    cpus: 0.5
    mem_limit: 512m